<?php

/**  !!! DO NOT EDIT THIS FILE !!!
 *
 * File for editing:
 *      .metadata/page.json
 *
 * All metadata files are created autoamtically on first load.
 */

$version = '{version}';

$settings = [
    'lang'        => 'en',
    'languages'   => ['en' => 'English', 'sk' => "Slovenčina"],
    'last_check'  => 0,
    'auto_update' => true,
    'title'       => 'BookPlayer',
    'subtitle'    => 'by <a href="https://v2.sk/" target="_blank" title="Version Two - versiontwo.sk - Websites, mobile apps, custom systems ...">v2.sk</a>',
];
initFilesIfNotPresent();

$settings = array_merge($settings, json_decode(file_get_contents('.metadata/page.json'), true));
checkForUpdate($settings);
$language = $_COOKIE['lang'] ?? $settings['lang'];

if (!array_key_exists($language, $settings['languages'])) {
    $language = 'en';
}

$translationLines = json_decode(file_get_contents('.metadata/lang/' . $language . '.json'), true);

$files = glob("*.mp3");
natsort($files);
$fileCount = count($files);

$bookDirectories = scanDirectories(getcwd());
?>
<!DOCTYPE html>
<html lang="<?= $language ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title><?= $settings['title'] ?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400&family=Roboto+Mono:wght@100;200&display=swap"
          rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js"
            integrity="sha512-GWzVrcGlo0TxTRvz9ttioyYJ+Wwk9Ck0G81D+eO63BaqHaJ3YZX9wuqjwgfcV/MrB2PhaVX9DkYVhbFpStnqpQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link rel="shortcut icon"
          href="data:image/svg+xml,%3Csvg version='1.0' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 64 64' enable-background='new 0 0 64 64' xml:space='preserve' fill='%23000000'%3E%3Cg id='SVGRepo_bgCarrier' stroke-width='0'%3E%3C/g%3E%3Cg id='SVGRepo_tracerCarrier' stroke-linecap='round' stroke-linejoin='round'%3E%3C/g%3E%3Cg id='SVGRepo_iconCarrier'%3E%3Cg%3E%3Cpath fill='%23F9EBB2' d='M56,62H10c-2.209,0-4-1.791-4-4s1.791-4,4-4h46V62z'%3E%3C/path%3E%3Cg%3E%3Cpath fill='%2345AAB8' d='M6,4v49.537C7.062,52.584,8.461,52,10,52h2V2H8C6.896,2,6,2.896,6,4z'%3E%3C/path%3E%3Cpath fill='%2345AAB8' d='M56,2H14v50h42h2v-2V4C58,2.896,57.104,2,56,2z'%3E%3C/path%3E%3C/g%3E%3Cg%3E%3Cpath fill='%23394240' d='M60,52V4c0-2.211-1.789-4-4-4H8C5.789,0,4,1.789,4,4v54c0,3.313,2.687,6,6,6h49c0.553,0,1-0.447,1-1 s-0.447-1-1-1h-1v-8C59.104,54,60,53.104,60,52z M6,4c0-1.104,0.896-2,2-2h4v50h-2c-1.539,0-2.938,0.584-4,1.537V4z M56,62H10 c-2.209,0-4-1.791-4-4s1.791-4,4-4h46V62z M56,52H14V2h42c1.104,0,2,0.896,2,2v46v2H56z'%3E%3C/path%3E%3Cpath fill='%23394240' d='M43,26H23c-0.553,0-1,0.447-1,1s0.447,1,1,1h20c0.553,0,1-0.447,1-1S43.553,26,43,26z'%3E%3C/path%3E%3Cpath fill='%23394240' d='M49,20H23c-0.553,0-1,0.447-1,1s0.447,1,1,1h26c0.553,0,1-0.447,1-1S49.553,20,49,20z'%3E%3C/path%3E%3Cpath fill='%23394240' d='M23,16h12c0.553,0,1-0.447,1-1s-0.447-1-1-1H23c-0.553,0-1,0.447-1,1S22.447,16,23,16z'%3E%3C/path%3E%3C/g%3E%3Cpath opacity='0.2' fill='%23231F20' d='M6,4v49.537C7.062,52.584,8.461,52,10,52h2V2H8C6.896,2,6,2.896,6,4z'%3E%3C/path%3E%3C/g%3E%3C/g%3E%3C/svg%3E">
    <style>
        /*include::styles.css*/
    </style>
</head>
<body>
<div class="settings-modal" id="settingsModal" style="display: none;">
    <div class="settings-modal-content">
        <span class="close">&times;</span>
        <?php if ($fileCount > 0): ?>
            <h2><?= $translationLines['settings_title']; ?></h2>
            <label for="volumeControl"><?= $translationLines['volume_control_label']; ?></label>
            <input type="range" min="0" max="100" value="100" class="slider" id="volumeControl">
            <br>
            <label for="speedSlider"><?= $translationLines['speed_title']; ?> </label>
            <div class="speed-control-container">
                <div class="slider-and-button">
                    <input type="range" id="speedSlider" min="0.25" max="2" step="0.05" value="1"
                           style="width: 70%;">
                    <button id="resetSpeedButton"
                            style="width: 25%;"><?= $translationLines['reset_button']; ?></button>
                </div>
            </div>
            <br>
        <?php endif; ?>
        <div class="language-selection">
            <label for="languageSelect"><?= $translationLines['language_title']; ?></label>
            <select id="languageSelect" onchange="audioPlayer.changeLanguage(this.value)">
                <?php
                foreach ($settings['languages'] as $newLang => $newLangTitle) {
                    echo '<option value="' . $newLang . '" ' . ($newLang == $language ? 'selected' : '') . '>' . $newLangTitle . '</option>';
                } ?>
            </select>
        </div>
    </div>
</div>

<svg class="settings-icon" id="settings-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
     onclick="window.openModal()">
    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
    <g id="SVGRepo_iconCarrier">
        <g>
            <line fill="none" y1="501" x1="303.1" y2="501" x2="302.1"></line>
            <g>
                <path d="m501,300.8v-91.7h-45.3c-5.3-22.4-14.3-43.3-26.4-62.1l32.9-32.7-64.9-64.6-33.4,33.3c-18.8-11.5-39.6-19.9-61.8-24.8v-47.2h-92.1v48.3c-22,5.4-42.6,14.4-61.1,26.4l-34.2-34-64.9,64.6 35.3,35.2c-2.8,4.6-5.3,9.2-7.7,14-7.5,14.3-13.2,30-17.1,45.7h-49.3v91.7h50.3c1.5,6 3.3,11.9 5.3,17.8 0.1,0.4 0.3,0.8 0.4,1.2 0,0.1 0.1,0.2 0.1,0.4 4.9,14.2 11.3,27.7 19.1,40.2l-35.5,35.3 64.9,64.6 35.1-34.9c18.3,11.5 38.6,20.2 60.2,25.4v48.1h91.1v-47.1c22.7-5 44-13.7 63.1-25.6l32.2,32 64.9-64.6-32.1-31.9c12-19.1 20.9-40.3 26-62.9h44.9zm-94.8,64l29.9,29.8-36.6,36.5-29.5-29.4c-24.7,18.9-54.4,31.7-86.7,36v42.4h-51.3v-42.7c-31.5-4.6-60.4-17.2-84.6-35.7l-31.6,31.5-36.6-36.5 32.4-31.3c-17.9-24-30-52.4-34.4-83.4h-45.3v-51.1h44l1.5-3.6c4.7-29.7 16.5-57.1 33.6-80.3l-32-31.9 36.6-36.5 31,31.9c24-18.5 52.8-31.2 84.1-36v-42.7h51.3v42.3c32,4.1 61.3,16.4 86,34.8l30.3-30.1 35.6,36.5-29.6,29.5c18.2,23.8 30.7,52.2 35.5,83.1h45.4v51.1h-44.7c-3.9,31.8-16.1,61.1-34.3,85.8z"></path>
                <path d="m257,143.4c-61.8,0-113.1,50-113.1,112.6s51.4,112.6 113.1,112.6 113.1-51.1 113.1-112.6-51.3-112.6-113.1-112.6zm0,204.3c-51.3,0-92.1-40.7-92.1-91.7 0-51.1 41.9-91.7 92.1-91.7s92.1,40.7 92.1,91.7c0.1,51.1-41.8,91.7-92.1,91.7z"></path>
            </g>
        </g>
    </g>
</svg>

<div class="main-container <?= $fileCount > 4 ? '' : 'center-content' ?>">
    <?php if (isset($settings['title'])): ?>
        <h1 class="page-title"><?= $settings['title'] ?></h1>
    <?php endif; ?>

    <?php if (isset($settings['subtitle'])): ?>
        <p class="page-subtitle"><?= $settings['subtitle'] ?></p>
    <?php endif; ?>

    <div class="book-container">
        <?php
        foreach ($bookDirectories as $bookSlug => $bookData) { ?>
            <div class="book-item <?= (!empty($bookData['subDirs']) ? 'multi' : '') ?>"
                 id="item-<?php echo $bookSlug; ?>"
                 data-subdir="<?php echo $bookData['directory']; ?>">
                <?php
                // Uncomment if you want to use these lines
                //echo '<button title="' . $translationLines['mark_as_listened_tooltip'] . '" class="mark-listened" onclick="audioPlayer.markAsListened(\'' . $hash . '\')"><i class="fa-solid fa-file-audio"></i></button>
                //      <button title="' . $translationLines['mark_as_not_listened_tooltip'] . '" class="mark-not-listened" onclick="audioPlayer.markAsNotListened(\'' . $hash . '\')" style="display:none;"><i class="fa-regular fa-file-audio"></i></button>';

                if (!empty($bookData['subDirs'])) { ?>
                    <div class="titles">
                        <?php
                        foreach ($bookData['subDirs'] as $subDirSlug => $subDirData) { ?>
                            <div class="audio-book">
                                <div class="mp3-title"><?php echo $subDirData['content']['title']; ?></div>
                                <div class="mp3-controls">
                                    <a id="play-<?php echo $subDirSlug; ?>" class="play-button"
                                       href="<?php echo $subDirData['directory']; ?>">
                                        <?php echo $translationLines['play']; ?>
                                    </a>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </div> <?php
                } else { ?>
                    <div class="audio-book">
                        <div class="mp3-title"><?php echo $bookData['content']['title']; ?></div>
                        <div class="mp3-controls">
                            <a id="play-<?php echo $bookSlug; ?>" class="play-button"
                               href="<?php echo $bookData['directory']; ?>">
                                <?php echo $translationLines['play']; ?>
                            </a>
                        </div>
                    </div>
                    <?php
                } ?>
            </div>

            <?php
        }
        ?>
    </div>

    <?php if ($fileCount > 0): ?>
        <div style="text-align: center">
            <button id="playResumeButton" onclick="audioPlayer.playOrResume()">
                <span id="playResumeIcon" class="fa fa-play"></span>
                <span id="playResumeText"><?= $translationLines['play']; ?></span>
            </button>

        </div>

        <div class="mp3-container">
            <?php

            foreach ($files as $file) {
                $encodedFile  = rawurlencode($file);
                $fileJsonData = getMP3Details($file); // Get details including duration

                $duration    = $fileJsonData['duration'];
                $hash        = $fileJsonData['hash'];
                $title       = $fileJsonData['title'] ?? htmlspecialchars($file);
                $description = $fileJsonData['description'] ?? null;

                // Convert duration to minutes and seconds format
                $minutes = floor($duration / 60);
                $seconds = str_pad((int)$duration % 60, 2, "0", STR_PAD_LEFT);

                $formattedDuration = sprintf("%02d:%02d", $minutes, $seconds);

                echo '<div class="mp3-item" id="item-' . $hash . '" data-filename="' . $encodedFile . '" data-duration="' . $formattedDuration . '">';
                echo '<button title="' . $translationLines['mark_as_listened_tooltip'] . '" class="mark-listened" onclick="audioPlayer.markAsListened(\'' . $hash . '\')"><i class="fa-solid fa-file-audio"></i></button>
                      <button title="' . $translationLines['mark_as_not_listened_tooltip'] . '" class="mark-not-listened" onclick="audioPlayer.markAsNotListened(\'' . $hash . '\')" style="display:none;"><i class="fa-regular fa-file-audio"></i></button>';
                echo '<div class="mp3-title" onclick="audioPlayer.toggleDescription(\'' . $hash . '\')" >' . $title;
                if (!is_null($description)) {
                    echo '&nbsp;<span class="expand-caret caret-' . $hash . '">&#9660;</span>';
                }
                echo '</div>';
                echo '<div class="mp3-controls">';
                echo '<button id="play-' . $hash . '" class="play-button" onclick="audioPlayer.playAudio(\'' . $hash . '\')">' . $translationLines['play'] . '</button>';
                echo '<div class="progress-bar" onclick="audioPlayer.seekAudio(event, \'' . $hash . '\')"><div class="progress-bar-inner"></div></div>';
                echo '<div class="time-info">00:00 / ' . $formattedDuration . '</div>'; // Use the formatted duration here
                echo '</div>';
                if (!is_null($description)) {
                    echo '<div class="mp3-description" onclick="audioPlayer.toggleDescription(\'' . $hash . '\')" id="desc-' . $hash . '">' . htmlspecialchars($description) . '</div>';
                }
                echo '<audio preload="metadata" onloadedmetadata="audioPlayer.updateTimeInfo(\'' . $hash . '\')" ontimeupdate="audioPlayer.updateProgress(\'' . $hash . '\')" id="audio-' . $hash . '" data-hash="' . $hash . '"></audio>';
                echo '</div>';
            }

            ?>
        </div>
    <?php endif; ?>
</div>

<script>
    /*include::javascript.js*/
</script>
</body>
</html>

/*include::php_functions.php*/

/*include::mpegaudio.php*/